name: ligtascommute_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  http: ^1.5.0
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  permission_handler: ^11.0.1
  mobile_scanner: ^6.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
